#!/usr/bin/env bash
# Script installs nginx when executed and opens port 80

sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start
sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www/html
echo 'Hello World!' > /var/www/html/index.html
