#!/usr/bin/env bash
# Script to configure server to redirect 301 moved permanently

sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i 's/^server {/server {\n\trewrite \^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default
sudo service nginx restart
