#!/usr/bin/env bash
# Script configures Nginx server to have a custom 404 page
# that contains string "Ceci n'est pas une page"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i 's/^server {/server {\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/' /etc/nginx/sites-available/default
sudo service nginx restart
