#!/usr/bin/env bash
# Display content of the file /etc/passwd
while read -r LINE
do
	USERNAME=$(echo "$LINE" | cut -d ':' -f 1)
	GROUP_ID=$(echo "$LINE" | cut -d ':' -f 4)
	USER_ID=$(echo "$LINE" | cut -d ':' -f 3)
	HOME_DIRECTORY=$(echo "$LINE" | cut -d ':' -f 6)
	COMMAND_SHELL=$(echo "$LINE" | cut -d ':' -f 7)
	PASSWORD=$(echo "$LINE" | cut -d ':' -f 2)
	USER_ID_INFO=$(echo "$LINE" | cut -d ':' -f 5)
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < /etc/passwd
