#!/usr/bin/env bash
# Script displays the content of the current directory in list format
# where only the part of the name after the first dash is displayed
for each in *
do
	echo "$each" | cut -d '-' -f 2
done
