#!/usr/bin/env bash
# script configures an ubuntu server /etc/hosts file
sudo cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo '8.8.8.8	facebook.com' >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
sudo rm ~/hosts.new
